name: retail_tax_filing_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # For state management
  http: ^1.0.0 # For making HTTP requests
  shared_preferences: ^2.0.15 # For storing user data locally
  flutter_secure_storage: ^9.2.4 # For secure storage of sensitive information
  intl: ^0.20.2 # For date and currency formatting
  firebase_core: 
  firebase_auth: 
  file_picker: 
  multi_select_flutter: ^4.0.0
  flutter_form_builder: 
  flutter_credit_card:
  flutter_inappwebview: ^6.0.0
  image_picker: ^1.1.2 
  cloud_firestore:
  firebase_auth_platform_interface:
  flutter_masked_text2:
  
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.10
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/home.jpg


  